CREATE DATABASE IF NOT EXISTS OFICINA_RENNAN_CORRECAO

USE OFICINA_RENNAN_CORRECAO

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    TELEFONE CHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    STATUS_CLIENTE ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS VEICULOS (
  ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
  PLACA CHAR(8) NOT NULL UNIQUE,
  TIPO_VEICULO ENUM ('CARRO', 'MOTO', 'CAMINHAO') DEFAULT 'CARRO',
  COR VARCHAR(20),
  QUILOMETRAGEM FLOAT,
  TIPO_MOTOR ENUM ('ELETRICO', 'COMBUSTAO'),
  DATA_CADASTRO DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP)
)

CREATE TABLE IF NOT EXISTS MARCAS (
  ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
  ANO_LANCAMENTO YEAR,
  PAIS_ORIGEM VARCHAR(60),
  STATUS_MARCA ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
  NOME_MARCA VARCHAR(30) NOT NULL,
  SITE_MARCA VARCHAR(100)
)

create table if NOT exists modelos (
  ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
  COR VARCHAR(20),
  ANO_MODELO YEAR,
  VALOR_MODELO DECIMAL(10,2),
  CATEGORIA ENUM ('SUV', 'HATCH', 'SEDAN', 'MOTO ESPORTIVA'),
  NOME_MODELO ENUM ('ATIVO', 'INATIVO'),
  DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
  ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(20) NOT NULL,
  CPF_FUNCIONARIO CHAR(14) UNIQUE NOT NULL,
  CARGO VARCHAR(50) NOT NULL,
  SALARIO DECIMAL(10,2) NOT NULL,
  STATUS_FUNCIONARIO ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO'
)

CREATE TABLE IF NOT EXISTS SERVICOS (
  ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_SERVICO VARCHAR(60) NOT NULL,
  DESCRICAO_PROBLEMA VARCHAR(250) NOT NULL,
  PRECO_SERVICO DECIMAL (10,2) DEFAULT 0.00 NOT NULL,
  DATA_INICIO DATETIME NOT NULL,
  DATA_TERMINO DATETIME NOT NULL,
  STATUS_SERVICO ENUM ('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE',
  DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS PECAS (
  ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
  TAMANHO VARCHAR (10) NOT NULL,
  VALOR_PECA DECIMAL (10,2),
  NOMA_PECA VARCHAR (50) NOT NULL,
  VALIDADE DATE NOT NULL,
  STATUS_PECA ENUM ('DISPONIVEL', 'INDISPONIVEL'),
  QNTD_PECA INT,
  DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVICO (
  ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
  PRIORIDADE ENUM ('URGENTE', 'SIMPLES') NOT NULL DEFAULT 'SIMPLES',
  PRAZO_FINAL DATE NOT NULL,
  RANKING_ORDEM VARCHAR (40) NOT NULL,
  DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  TIPO_CASO VARCHAR(250) NOT NULL,
  STATUS_SERVICO ENUM ('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE'
)

create table Pagamentos (
    Id_Pagamento int auto_increment primary key,
    valor_Total decimal(10, 2) not null default 000.00,
    forma_Pagamento enum('Debito', 'Credito', 'PIX') default 'Debito',
    data_Vencimento date not null,
    status_Pagamento varchar(30) not null,
    comprovante int,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
  ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(100) NOT NULL,
  CNPJ CHAR (18) NOT NULL UNIQUE,
  TELEFONE_CONTATO VARCHAR(14) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  INSCRICAO_ESTADUAL CHAR (10),
  SEGMENTO_FORNECEDOR VARCHAR(50) NOT NULL,
  ENDERECO_FORNECEDOR VARCHAR(100) NOT NULL,
  DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

ALTER TABLE CLIENTES ADD IDADE INT;

ALTER TABLE FUNCIONARIOS ADD ENDERECO VARCHAR(100);

ALTER TABLE MARCAS ADD OBSERVACAO VARCHAR(200);

ALTER TABLE MODELOS ADD TIPO_MODELO VARCHAR (50);

ALTER TABLE ORDEM_DE_SERVICO ADD AREA_SERVICO VARCHAR (60) NOT NULL;

ALTER TABLE PECAS ADD PESO FLOAT NOT NULL;

ALTER TABLE SERVICOS ADD OBSERVACAO VARCHAR(60);

ALTER TABLE VEICULOS ADD MODELO VARCHAR (60);

ALTER TABLE FORNECEDOR ADD TIPO_ENVIO VARCHAR(50);

ALTER TABLE PAGAMENTOS ADD DESCONTO DECIMAL (10,2);

ALTER TABLE CLIENTES DROP COLUMN IDADE

RENAME TABLE MODELOS TO MODELOS_FAB

-- VIZUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- VIZUALIZAR TABELAS DE BD
SHOW TABLES;

--DESCRIÇÃO SOBRE INFORMAÇÕES DAS TABELAS
DESCRIBE CLIENTES
